#!/bin/bash
clear
#echo "test"
#echo "enter the name of the file that you want to create"
#read name
#echo $name
#file="$name.txt"
#touch $file
#echo "enter intro"
#read intro
#cho $intro > $file
pathh=$(pwd)
echo $pathh
cd
echo $pathh
fin=$pathh/trainning.py
echo $fin
python3 $fin